TestModule: PythonWithCpp.cpp TestModule.py
	g++ PythonWithCpp.cpp -o PythonWithCpp -I/usr/include/python2.6/ -L/usr/lib/python2.6 -lpthread -ldl -lm -lutil -lpython2.6
	
clean:
	rm PythonWithCpp TestModule.pyc